//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class experts_expertises
    {
        public int id_expertises_experts { get; set; }
        public int id_expertise { get; set; }
        public int id_expert { get; set; }
        public bool role { get; set; }
        public int id_status { get; set; }
    
        public virtual expertises expertises { get; set; }
        public virtual experts experts { get; set; }
        public virtual Status Status { get; set; }
    }
}
