//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_expertiseEntities : DbContext
    {
        public db_expertiseEntities()
            : base("name=db_expertiseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<criterions> criterions { get; set; }
        public virtual DbSet<expertises> expertises { get; set; }
        public virtual DbSet<expertises_criterions> expertises_criterions { get; set; }
        public virtual DbSet<experts> experts { get; set; }
        public virtual DbSet<experts_expertises> experts_expertises { get; set; }
        public virtual DbSet<marks> marks { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<projects_expertises> projects_expertises { get; set; }
        public virtual DbSet<results_experts> results_experts { get; set; }
        public virtual DbSet<results_expertise> results_expertise { get; set; }
        public virtual DbSet<results_expertises_criterions> results_expertises_criterions { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<factors> factors { get; set; }
        public virtual DbSet<marks_factors> marks_factors { get; set; }
        public virtual DbSet<marks_ribs> marks_ribs { get; set; }
        public virtual DbSet<ribs> ribs { get; set; }
        public virtual DbSet<results_factors> results_factors { get; set; }
        public virtual DbSet<results_ribs> results_ribs { get; set; }
    }
}
